title: SEOmetoden | Är du redo för fler kunder från Google?
baseURL: /
params:
  layout_type: boxed
  style: classic
  palette: green
  mode: light
  base_font: serif
  footer:
    type: footer
    logo: /images/logo.png
    logo_alt: seometoden-logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        url: /about
        style: link
      - type: action
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Information
    secondary_nav_links:
      - type: action
        label: Blogg
        url: /blogg
        style: link
      - type: action
        label: Vanliga frågor
        url: /vanliga-fragor
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Policy
    tertiary_nav_links:
      - type: action
        label: Villkor
        url: /villkor
        style: link
      - type: action
        label: Privatpolicy
        url: /privatpolicy
        style: link
    has_social: true
    social_links:
      - type: action
        label: YouTube
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
    content: '&copy; 2021  SEOmetoden.se'
  domain: 'https://seometoden.se'
  favicon: /images/favicon.png
  taxonomies: null
  stub: stub
  header:
    title: SEOmetoden
    logo_alt: logo
    has_primary_nav: true
    primary_nav_links:
      - label: Blogg
        url: /blogg
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
      - label: Vanliga frågor
        url: /vanliga-fragor
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
    has_secondary_nav: true
    secondary_nav_links:
      - label: YouTube
        url: /kontakt
        style: secondary
        has_icon: true
        icon: youtube
        icon_position: right
        new_window: false
        no_follow: false
        type: action
      - label: Inled en diskussion
        url: 'https://forms.gle/1WBVyEi9DQYp1C9XA'
        style: primary
        has_icon: false
        icon: arrow-right
        icon_position: right
        new_window: true
        no_follow: false
        type: action
    has_anncmnt: true
    anncmnt_content: >
      Den här webbplatsen använder sig av kakor för att förbättra din
      upplevelse.
    anncmnt_align: left
    anncmnt_is_home_only: false
    anncmnt_has_close: false
    anncmnt_id: lorem-ipsum
    type: header
    logo: /images/logo.png
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer: null
    unsafe: true
