title: SEOmetoden | Är du redo för fler kunder från Google?
baseURL: /
enableEmoji: true
params:
  layout_type: boxed
  style: classic
  palette: green
  mode: light
  base_font: serif
  header:
    type: header
    logo_alt: seometoden-logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        label: Blogg
        url: /blogg
        style: link
      - type: action
        label: Vanliga Frågor
        url: /vanliga-fragor
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        label: Prata med Dennis idag
        url: /kontakt
        style: primary
    has_anncmnt: true
    anncmnt_content: >
      Den här webbplatsen använder kakor för att förbättra din upplevelse.
      [**Läs mer**](www.google.com).
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
    logo: /images/logo.png
  footer:
    type: footer
    logo: /images/logo.png
    logo_alt: seometoden-logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        url: /about
        style: link
      - type: action
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Information
    secondary_nav_links:
      - type: action
        label: Blogg
        url: /blog/category/news
        style: link
      - type: action
        label: Vanliga frågor
        url: /blog/category/general
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Policy
    tertiary_nav_links:
      - type: action
        label: Terms & Conditions
        url: /terms-conditions
        style: link
      - type: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: false
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        label: GitHub
        url: 'https://github.com/'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - type: action
        label: YouTube
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
      - type: action
        label: Vimeo
        url: 'https://vimeo.com/'
        style: link
        has_icon: true
        icon: vimeo
        icon_position: center
        new_window: true
    content: '&copy; 2021  SEOmetoden'
  domain: 'https://seometoden.se'
  favicon: /images/incredible-turmeric.png
  taxonomies: null
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer: null
    unsafe: true
